spring:
  rabbitmq:
    host: 34.87.77.231
    port: 30069
    username: admin
    password: grove1234
    listener:
      simple:
        prefetch: 10

  datasource:
    url: jdbc:mysql://35.240.134.127:3306/i2m
    username: root
    password: 123
    sqlScriptEncoding: UTF-8
