spring:
  datasource:
    url: jdbc:mysql://35.240.134.127:3306/i2m
    username: root
    password: 123
    sqlScriptEncoding: UTF-8

  data:
    mongodb:
      uri: mongodb://35.240.134.127:27017/i2m

  rabbitmq:
    host: 35.240.145.156
    port: 30069
    username: admin
    password: grove1234
    listener:
      simple:
        prefetch: 10
