spring:
  rabbitmq:
    host: 35.240.130.146
    port: 30069
    username: admin
    password: grove1234
  data:
    mongodb:
      uri: mongodb://root:grove1234@35.240.130.146:30068/i2m?authSource=admin
