spring:
  datasource:
    url: jdbc:mysql://localhost:3306/i2m
    username: root
    password: 123456789
    sqlScriptEncoding: UTF-8

  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

  rabbitmq:
    host: 35.240.130.146
    port: 30069
    username: admin
    password: grove1234

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: flowershower282@gmail.com
    password: vannguyen2802
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 236035663191-2iismpr3nn134jgfquoaqnk422hjelj7.apps.googleusercontent.com
            clientSecret: ZFf4ECJi-tEywvVGQtk9dL1B
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
app:
  jwtSecret: 926D96C90030DD58429D2751AC1BDBBC
  jwtExpirationInMs: 864000000
  credentialPath: ${CREDENTIAL_PATH:i2m-credentials.json}
  oauth2:
    authorizedRedirectUris:
      - ${AUTHORIZED_REDIRECT_URI:http://localhost:3000}


