spring:
  datasource:
    url: jdbc:mysql://${MYSQL_URL:localhost}:3306/i2m
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:123456789}
    sqlScriptEncoding: UTF-8

  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

  rabbitmq:
    host: ${RABBITMQ_HOST:35.240.130.146}
    port: ${RABBITMQ_PORT:30069}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:grove1234}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:flowershower282@gmail.com}
    password: ${MAIL_PASSWORD:vannguyen2802}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENTID:236035663191-2iismpr3nn134jgfquoaqnk422hjelj7.apps.googleusercontent.com}
            clientSecret: ${GOOGLE_CLIENT_SECRET:ZFf4ECJi-tEywvVGQtk9dL1B}
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
app:
  jwtSecret: ${APP_JWT_SECRET:926D96C90030DD58429D2751AC1BDBBC}
  jwtExpirationInMs: ${APP_JWT_EXPIRATION:864000000}
  credentialPath: ${CREDENTIAL_PATH:i2m-credentials.json}
  oauth2:
    authorizedRedirectUris:
      - ${AUTHORIZED_REDIRECT_URI:http://localhost:3000}
